// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Reg00/gameReview/internal/infrastructure/appctx"
	"github.com/Reg00/gameReview/internal/infrastructure/config"
	"github.com/Reg00/gameReview/internal/infrastructure/igdb"
	"github.com/Reg00/gameReview/internal/infrastructure/storage"
	"github.com/Reg00/gameReview/internal/infrastructure/web"
	"github.com/Reg00/gameReview/internal/infrastructure/web/routes"
)

// Injectors from wire.go:

func InitWebServer() (*web.Server, error) {
	coreContext := appctx.Register()
	configuration := config.Register()
	igdbClient := igdb.Register(configuration)
	gormStorage, err := gorm.Register(configuration)
	if err != nil {
		return nil, err
	}
	engine, err := routes.Register(igdbClient, gormStorage)
	if err != nil {
		return nil, err
	}
	server := web.Register(coreContext, configuration, engine)
	return server, nil
}
